import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

const dictionary = {
  'nav.home': { en: 'Home', ur: 'ہوم' },
  'nav.catalog': { en: 'Catalog', ur: 'کیٹلاگ' },
  'nav.tryOn': { en: 'Try-On', ur: 'ٹرائی آن' },
  'nav.skinAnalysis': { en: 'Skin Tone', ur: 'رنگت' },
  'nav.measurements': { en: 'Measurements', ur: 'پیمائش' },
  'nav.tracking': { en: 'Tracking', ur: 'ٹریکنگ' },
  'nav.cart': { en: 'Cart', ur: 'کارٹ' },
  'nav.login': { en: 'Login', ur: 'لاگ ان' },
  'nav.logout': { en: 'Logout', ur: 'لاگ آؤٹ' },
  'nav.admin': { en: 'Admin', ur: 'ایڈمن' },
  'nav.skinTone': { en: 'Skin Tone', ur: 'رنگت' },
  'nav.deliveries': { en: 'Deliveries', ur: 'ڈیلیوری' },

  'admin.inventory': { en: 'Inventory', ur: 'انوینٹری' },
  'admin.khata': { en: 'Khata', ur: 'کھاتہ' },
  'admin.expenses': { en: 'Expenses', ur: 'اخراجات' },
  'admin.revenue': { en: 'Total Revenue', ur: 'کل آمدنی' },
  'admin.profit': { en: 'Net Profit', ur: 'خالص منافع' },
  'admin.stock': { en: 'Stock', ur: 'اسٹاک' },
  'admin.addStock': { en: 'Add New Stock', ur: 'نیا اسٹاک شامل کریں' },
  'admin.recordEntry': { en: 'Record Entry', ur: 'انٹری درج کریں' },
  'admin.lowStock': { en: 'LOW STOCK!', ur: 'اسٹاک کم ہے!' },
  'admin.analytics.tab': { en: 'Analytics', ur: 'تجزیات' },
  'admin.khataTab': { en: 'Khata', ur: 'کھاتہ' },
  'admin.invoicesTab': { en: 'Invoices', ur: 'انوائسز' },
  'admin.inventoryTab': { en: 'Inventory', ur: 'انوینٹری' },
  'admin.settingsTab': { en: 'Settings', ur: 'ترتیبات' },
  'admin.accountSettings': { en: 'Account Settings', ur: 'اکاؤنٹ کی ترتیبات' },
  'admin.currentPassword': { en: 'Current Password', ur: 'موجودہ پاس ورڈ' },
  'admin.newPassword': { en: 'New Password', ur: 'نیا پاس ورڈ' },
  'admin.confirmNewPassword': { en: 'Confirm New Password', ur: 'نیا پاس ورڈ تصدیق' },
  'admin.changePasswordBtn': { en: 'Update Password', ur: 'پاس ورڈ اپڈیٹ کریں' },
  'admin.passwordUpdated': { en: 'Password updated successfully', ur: 'پاس ورڈ کامیابی سے اپڈیٹ ہو گیا' },
  'admin.analytics.title': { en: 'Customer & Sales Analytics', ur: 'گاہک اور فروخت کے تجزیات' },
  'admin.analytics.ordersByMonth': { en: 'Monthly Orders & Revenue (Last 12 Months)', ur: 'ماہانہ آرڈرز اور آمدنی (آخری 12 مہینے)' },
  'admin.analytics.popularCategories': { en: 'Popular Garment Categories', ur: 'مقبول ملبوسات کی کیٹیگریز' },
  'admin.analytics.repeatRate': { en: 'Repeat Customer Rate', ur: 'بار بار آنے والے گاہکوں کی شرح' },
  'admin.analytics.avgLeadTime': { en: 'Average Lead Time', ur: 'اوسط وقتِ تکمیل' },
  'admin.analytics.repeatRateDesc': { en: 'Percentage of customers who placed 2 or more orders', ur: 'ان گاہکوں کی شرح جنہوں نے 2 یا اس سے زائد آرڈرز دیے' },
  'admin.analytics.avgLeadTimeDesc': { en: 'Average days from order confirmation to delivery', ur: 'آرڈر کی تصدیق سے لے کر ڈیلیوری تک کے اوسط دن' },
  'admin.analytics.repeatCustomers': { en: 'Repeat Customers', ur: 'بار بار آنے والے گاہک' },
  'admin.analytics.totalCustomers': { en: 'Total Customers', ur: 'کل گاہک' },
  'admin.analytics.days': { en: 'Days', ur: 'دن' },
  'admin.analytics.noData': { en: 'No analytics data available to display', ur: 'دکھانے کے لیے کوئی تجزیاتی ڈیٹا دستیاب نہیں ہے' },
  'admin.analytics.loading': { en: 'Loading analytics data...', ur: 'تجزیاتی ڈیٹا لوڈ ہو رہا ہے...' },
  'admin.analytics.error': { en: 'Failed to load analytics', ur: 'تجزیات لوڈ کرنے میں ناکامی' },
  'admin.analytics.revenue': { en: 'Revenue (Rs.)', ur: 'آمدنی (روپے)' },
  'admin.analytics.orders': { en: 'Orders Count', ur: 'آرڈرز کی تعداد' },
  'admin.analytics.categoryCount': { en: 'Items Ordered', ur: 'آرڈر کردہ اشیاء' },

  'hero.title': { en: 'Premium Men\'s Bespoke Tailoring', ur: 'پریمیم مردانہ ملبوسات کی سلائی' },
  'hero.subtitle': { en: 'Experience the perfect fit with our AI-powered skin tone analysis and virtual try-on technology.', ur: 'ہمارے AI ٹیکنالوجی کے ذریعے اپنی جلد کے مطابق بہترین رنگ اور فٹنگ حاصل کریں۔' },
  'hero.badge': { en: 'New Season Collection', ur: 'نئی کلیکشن' },
  'hero.explore': { en: 'Explore Collection', ur: 'کلیکشن دیکھیں' },
  'hero.tryOn': { en: 'Virtual Try-On', ur: 'ورچوئل ٹرائی آن' },
  'hero.cta.shop': { en: 'Shop Collection', ur: 'کلیکشن دیکھیں' },
  'hero.cta.tryon': { en: 'Virtual Try-On', ur: 'ورچوئل ٹرائی آن' },

  'catalog.title': { en: 'Premium Collection', ur: 'پریمیم کلیکشن' },
  'catalog.titleA': { en: 'Premium', ur: 'پریمیم' },
  'catalog.titleB': { en: 'Collection', ur: 'کلیکشن' },
  'catalog.subtitle': { en: 'Discover our latest bespoke designs', ur: 'ہمارے تازہ ترین ڈیزائن دیکھیں' },
  'catalog.allProducts': { en: 'All Products', ur: 'تمام ملبوسات' },
  'catalog.price': { en: 'Rs.', ur: 'روپے' },
  'catalog.addToCart': { en: 'Add to Cart', ur: 'کارٹ میں شامل کریں' },
  'catalog.viewDetails': { en: 'View Details', ur: 'تفصیلات دیکھیں' },
  'catalog.search': { en: 'Search products...', ur: 'مصنوعات تلاش کریں...' },
  'catalog.filters': { en: 'Filters', ur: 'فلٹرز' },
  'catalog.categories': { en: 'Categories', ur: 'کیٹیگریز' },
  'catalog.brands': { en: 'Brands', ur: 'برانڈز' },
  'catalog.allBrands': { en: 'All Brands', ur: 'تمام برانڈز' },
  'catalog.fabricType': { en: 'Fabric Type', ur: 'کپڑے کی قسم' },
  'catalog.wearType': { en: 'Wear Type', ur: 'پہننے کی قسم' },
  'catalog.traditional': { en: 'Traditional', ur: 'روایتی' },
  'catalog.formal': { en: 'Formal', ur: 'فارمل' },
  'catalog.priceRange': { en: 'Price Range', ur: 'قیمت کی حد' },
  'catalog.clearFilters': { en: 'Clear All', ur: 'تمام فلٹرز ختم کریں' },
  'catalog.stitched': { en: 'Stitched', ur: 'سلے ہوئے' },
  'catalog.unstitched': { en: 'Unstitched', ur: 'بغیر سلے' },
  'catalog.custom': { en: 'Custom', ur: 'کسٹم' },
  'catalog.sizesCount': { en: 'Sizes', ur: 'سائز' },
  'catalog.min': { en: 'Min', ur: 'کم از کم' },
  'catalog.max': { en: 'Max', ur: 'زیادہ سے زیادہ' },
  'catalog.previous': { en: 'Previous', ur: 'پچھلا' },
  'catalog.next': { en: 'Next', ur: 'اگلا' },
  'catalog.noProducts': { en: 'No products found', ur: 'کوئی پروڈکٹ نہیں ملی' },
  'catalog.tryFilters': { en: 'Try adjusting your filters', ur: 'اپنے فلٹرز تبدیل کر کے دیکھیں' },

  'measurements.title': { en: 'My Measurements', ur: 'میری پیمائش' },
  'measurements.subtitle': { en: 'Save your measurements for a perfect fit.', ur: 'بہترین فٹنگ کے لیے اپنی پیمائش محفوظ کریں۔' },
  'measurements.lookup': { en: 'Lookup by Code', ur: 'کوڈ سے تلاش کریں' },
  'measurements.load': { en: 'Load', ur: 'لوڈ کریں' },
  'measurements.book': { en: 'Book Appointment', ur: 'وقت لیں' },
  'measurements.noSaved': { en: 'No measurements saved yet', ur: 'ابھی تک کوئی پیمائش محفوظ نہیں کی گئی' },
  'measurements.selectGarment': { en: 'Select a garment type to start adding your measurements', ur: 'پیمائش شروع کرنے کے لیے لباس کا انتخاب کریں' },
  'measurements.addNew': { en: 'Add New Measurement', ur: 'نئی پیمائش شامل کریں' },
  'measurements.fields.count': { en: 'measurements', ur: 'پیمائشیں' },
  'measurements.type': { en: 'Type', ur: 'قسم' },
  'measurements.updated': { en: 'Updated', ur: 'تبدیل کیا گیا' },
  'measurements.edit': { en: 'Edit', ur: 'تبدیل کریں' },
  'measurements.new': { en: 'New', ur: 'نئی' },
  'measurements.label': { en: 'Label (Optional)', ur: 'نام (اختیاری)' },
  'measurements.howTo': { en: 'How to measure', ur: 'پیمائش کا طریقہ' },
  'measurements.save': { en: 'Save & Generate Code', ur: 'محفوظ کریں اور کوڈ حاصل کریں' },
  'measurements.update': { en: 'Update Measurements', ur: 'پیمائش اپ ڈیٹ کریں' },
  'measurements.success.saved': { en: 'Measurements saved!', ur: 'پیمائش محفوظ ہو گئی!' },
  'measurements.success.updated': { en: 'Measurements updated!', ur: 'پیمائش اپ ڈیٹ ہو گئی!' },
  'measurements.success.deleted': { en: 'Measurement deleted', ur: 'پیمائش حذف کر دی گئی' },
  'measurements.success.copied': { en: 'Copied', ur: 'کاپی ہو گیا' },
  'measurements.error.notFound': { en: 'Measurement code not found', ur: 'پیمائش کا کوڈ نہیں ملا' },
  'measurements.error.fillAll': { en: 'Please fill all fields', ur: 'براہ کرم تمام خانے پُر کریں' },

  'measurements.appointment.title': { en: 'Book Measurement Appointment', ur: 'پیمائش کے لیے وقت لیں' },
  'measurements.appointment.date': { en: 'Preferred Date', ur: 'پسندیدہ تاریخ' },
  'measurements.appointment.time': { en: 'Preferred Time', ur: 'پسندیدہ وقت' },
  'measurements.appointment.phone': { en: 'Phone Number', ur: 'فون نمبر' },
  'measurements.appointment.notes': { en: 'Notes (Optional)', ur: 'نوٹ (اختیاری)' },
  'measurements.appointment.submit': { en: 'Submit Request', ur: 'درخواست بھیجیں' },
  'measurements.appointment.myTitle': { en: 'My Measurement Appointments', ur: 'میری پیمائش کی اپوائنٹمنٹس' },
  'measurements.appointment.phoneRequired': { en: 'Please enter your phone number', ur: 'براہ کرم اپنا فون نمبر درج کریں' },
  'measurements.appointment.dateRequired': { en: 'Please select preferred date', ur: 'براہ کرم پسندیدہ تاریخ منتخب کریں' },
  'measurements.appointment.submitted': { en: 'Appointment request submitted! Admin will review and approve soon.', ur: 'درخواست جمع ہو گئی ہے! ایڈمن جلد تصدیق کرے گا۔' },
  'measurements.appointment.empty': { en: 'No appointment booked yet. Can’t take measurements yourself? Book a session with our Master Tailor.', ur: 'ابھی تک کوئی اپوائنٹمنٹ بک نہیں ہوئی۔ خود پیمائش نہیں لے سکتے؟ ہمارے ماسٹر ٹیلر سے وقت لیں۔' },
  'measurements.appointment.bookNew': { en: 'Book New Appointment', ur: 'نیا وقت لیں' },
  'admin.appointments': { en: 'Appointments', ur: 'اپوائنٹمنٹس' },
  'admin.appointments.title': { en: 'Customer Measurement Appointments', ur: 'گاہکوں کی پیمائش کی اپوائنٹمنٹس' },
  'admin.appointments.desc': { en: 'Review, approve, or decline customer appointment requests for in-person measurements.', ur: 'گاہکوں کی پیمائش کی درخواستوں کا جائزہ لیں، منظور کریں یا مسترد کریں۔' },
  'measurements.tutorial.title': { en: 'Measurement Tutorial', ur: 'پیمائش کا طریقہ کار' },

  // ── AI Measurements ────────────────────────────────────────────────────────
  'nav.aiMeasure': { en: 'AI Measure', ur: 'AI پیمائش' },
  'aimeasure.title': { en: 'AI Body Measurement', ur: 'AI جسمانی پیمائش' },
  'aimeasure.subtitle': { en: 'Upload your photos and let AI estimate your body measurements', ur: 'اپنی تصاویر اپ لوڈ کریں اور AI سے جسمانی پیمائش کا اندازہ لگائیں' },
  'aimeasure.banner.title': { en: 'AI Estimated — Verify Before Saving', ur: 'AI اندازہ — محفوظ کرنے سے پہلے تصدیق کریں' },
  'aimeasure.banner.desc': { en: 'AI measurements are approximate. Always verify with a tape measure before placing an order.', ur: 'AI پیمائشیں تقریبی ہیں۔ آرڈر دینے سے پہلے ہمیشہ فیتے سے تصدیق کریں۔' },
  'aimeasure.frontPhoto': { en: 'Front Photo', ur: 'سامنے کی تصویر' },
  'aimeasure.sidePhoto': { en: 'Side Photo', ur: 'سائیڈ تصویر' },
  'aimeasure.uploadFront': { en: 'Upload front view', ur: 'سامنے سے تصویر اپ لوڈ کریں' },
  'aimeasure.uploadSide': { en: 'Upload side view', ur: 'سائیڈ سے تصویر اپ لوڈ کریں' },
  'aimeasure.photoTip': { en: 'Full body, well-lit, fitted clothes', ur: 'پورا جسم، روشنی میں، فٹ کپڑے' },
  'aimeasure.photoReady': { en: 'Ready', ur: 'تیار' },
  'aimeasure.optionalInputs': { en: 'Optional — Improve Accuracy', ur: 'اختیاری — درستگی بڑھائیں' },
  'aimeasure.gender': { en: 'Gender', ur: 'جنس' },
  'aimeasure.male': { en: 'Male', ur: 'مرد' },
  'aimeasure.female': { en: 'Female', ur: 'عورت' },
  'aimeasure.other': { en: 'Other', ur: 'دیگر' },
  'aimeasure.height': { en: 'Height (cm)', ur: 'قد (سینٹی میٹر)' },
  'aimeasure.extractBtn': { en: 'Extract Measurements with AI', ur: 'AI سے پیمائش حاصل کریں' },
  'aimeasure.analyzing': { en: 'Analyzing photos...', ur: 'تصاویر کا تجزیہ ہو رہا ہے...' },
  'aimeasure.reset': { en: 'Reset', ur: 'ری سیٹ' },
  'aimeasure.processing': { en: 'AI is analyzing your photos...', ur: 'AI آپ کی تصاویر کا تجزیہ کر رہا ہے...' },
  'aimeasure.processingDesc': { en: 'This usually takes 10-20 seconds', ur: 'اس میں عام طور پر 10-20 سیکنڈ لگتے ہیں' },
  'aimeasure.placeholder.title': { en: 'AI Results Will Appear Here', ur: 'AI نتائج یہاں آئیں گے' },
  'aimeasure.placeholder.desc': { en: 'Upload front and side photos, then click "Extract Measurements" to get AI-powered body estimates.', ur: 'سامنے اور سائیڈ تصاویر اپ لوڈ کریں، پھر AI اندازے حاصل کرنے کے لیے "پیمائش حاصل کریں" پر کلک کریں۔' },
  'aimeasure.conf.high': { en: 'High Confidence', ur: 'زیادہ اعتماد' },
  'aimeasure.conf.medium': { en: 'Medium Confidence', ur: 'درمیانہ اعتماد' },
  'aimeasure.conf.low': { en: 'Low Confidence', ur: 'کم اعتماد' },
  'aimeasure.results': { en: 'Estimated Measurements', ur: 'تخمینی پیمائش' },
  'aimeasure.fields': { en: 'fields', ur: 'فیلڈز' },
  'aimeasure.notes': { en: 'AI Notes', ur: 'AI نوٹس' },
  'aimeasure.saveBtn': { en: 'Save & Go to Measurements', ur: 'محفوظ کریں اور پیمائش پر جائیں' },
  'aimeasure.saving': { en: 'Saving...', ur: 'محفوظ ہو رہا ہے...' },
  'aimeasure.saveHint': { en: 'Measurements will be saved to your profile. You can edit them anytime.', ur: 'پیمائش آپ کے پروفائل میں محفوظ ہو جائے گی۔ آپ کسی بھی وقت تبدیل کر سکتے ہیں۔' },
  'aimeasure.success': { en: 'AI analysis complete! Review measurements below.', ur: 'AI تجزیہ مکمل! نیچے پیمائش دیکھیں۔' },
  'aimeasure.saved': { en: 'Measurements saved! Redirecting...', ur: 'پیمائش محفوظ ہو گئی! منتقل ہو رہا ہے...' },
  'aimeasure.error.bothPhotos': { en: 'Please upload both front and side photos', ur: 'براہ کرم سامنے اور سائیڈ دونوں تصاویر اپ لوڈ کریں' },
  'aimeasure.error.invalidImage': { en: 'Please select an image file', ur: 'براہ کرم تصویر فائل منتخب کریں' },
  'aimeasure.error.tooLarge': { en: 'Image must be under 10 MB', ur: 'تصویر 10 MB سے کم ہونی چاہیے' },
  'aimeasure.howItWorks': { en: 'How It Works', ur: 'یہ کیسے کام کرتا ہے' },
  'aimeasure.step1.title': { en: 'Take Two Photos', ur: 'دو تصاویر لیں' },
  'aimeasure.step1.desc': { en: 'Stand in front of a plain background. Take a front view and a side view in fitted clothes.', ur: 'سادہ پس منظر کے سامنے کھڑے ہوں۔ فٹ کپڑوں میں سامنے اور سائیڈ سے تصویر لیں۔' },
  'aimeasure.step2.title': { en: 'AI Analysis', ur: 'AI تجزیہ' },
  'aimeasure.step2.desc': { en: 'Our Gemini Vision AI analyzes proportions and estimates 8 key body measurements.', ur: 'ہمارا Gemini Vision AI تناسب کا تجزیہ کرتا ہے اور 8 اہم جسمانی پیمائشوں کا اندازہ لگاتا ہے۔' },
  'aimeasure.step3.title': { en: 'Review & Save', ur: 'جائزہ اور محفوظ' },
  'aimeasure.step3.desc': { en: 'Verify the AI estimates with a tape measure, adjust if needed, then save to your profile.', ur: 'AI اندازوں کی فیتے سے تصدیق کریں، ضرورت ہو تو درست کریں، پھر پروفائل میں محفوظ کریں۔' },

  'skintone.title': { en: 'Skin Tone Analysis', ur: 'جلد کا تجزیہ' },
  'skintone.subtitle': { en: 'Detect your skin tone for better fabric choices.', ur: 'بہتر لباس کے انتخاب کے لیے اپنی جلد کا رنگ معلوم کریں۔' },
  'skintone.upload': { en: 'Upload Photo', ur: 'تصویر اپ لوڈ کریں' },
  'skintone.analyze': { en: 'Analyze Skin Tone', ur: 'تجزیہ کریں' },
  'skintone.result': { en: 'Your Detected Tone', ur: 'آپ کی رنگت' },
  'skintone.recommendations': { en: 'Recommended Fabrics', ur: 'تجویز کردہ کپڑے' },

  'onboarding.title': { en: 'Welcome to TailorHub!', ur: 'TailorHub پر خوش آمدید!' },
  'onboarding.subtitle': { en: 'What would you like to do first?', ur: 'آپ پہلے کیا کرنا چاہیں گے؟' },
  'onboarding.skintone.title': { en: 'Analyze My Skin Tone', ur: 'جلد کا رنگ معلوم کریں' },
  'onboarding.skintone.desc': { en: 'Get personalized fabric color recommendations', ur: 'اپنی جلد کے مطابق رنگوں کے مشورے حاصل کریں' },
  'onboarding.catalog.title': { en: 'Browse Products', ur: 'مصنوعات دیکھیں' },
  'onboarding.catalog.desc': { en: 'Explore our catalog of premium men\'s garments', ur: 'ہمارے پریمیم مردانہ ملبوسات دیکھیں' },
  'onboarding.measurements.title': { en: 'Add My Measurements', ur: 'میری پیمائش شامل کریں' },
  'onboarding.measurements.desc': { en: 'Save your measurements for custom stitching', ur: 'کسٹم سلائی کے لیے اپنی پیمائش محفوظ کریں' },
  'onboarding.skip': { en: 'Skip for now', ur: 'ابھی چھوڑ دیں' },

  'skintone.prompt.title': { en: 'Start with Skin Tone Analysis', ur: 'جلد کے رنگ کے تجزیے سے شروع کریں' },
  'skintone.prompt.desc': { en: 'To get accurate recommendations, analyze your skin tone first.', ur: 'بہترین مشورے کے لیے پہلے اپنی جلد کا رنگ معلوم کریں۔' },
  'skintone.prompt.now': { en: 'Analyze Now', ur: 'ابھی معلوم کریں' },

  'tracking.title': { en: 'Order Tracking', ur: 'آرڈر ٹریکنگ' },
  'tracking.subtitle': { en: 'Track your order progress in real-time', ur: 'اپنے آرڈر کی پیشرفت دیکھیں' },
  'tracking.noOrders': { en: 'No orders yet', ur: 'ابھی تک کوئی آرڈر نہیں' },
  'tracking.progress': { en: 'Progress', ur: 'پیشرفت' },
  'tracking.status.pending': { en: 'Pending', ur: 'زیر التواء' },
  'tracking.status.confirmed': { en: 'Confirmed', ur: 'تصدیق شدہ' },
  'tracking.status.cutting': { en: 'Cutting', ur: 'کٹائی ہو رہی ہے' },
  'tracking.status.stitching': { en: 'Stitching', ur: 'سلائی ہو رہی ہے' },
  'tracking.status.processing': { en: 'Processing', ur: 'تیار ہو رہا ہے' },
  'tracking.status.ready': { en: 'Ready for Pickup', ur: 'تیار ہے' },
  'tracking.status.out_for_delivery': { en: 'Out for Delivery', ur: 'ڈیلیوری کے لیے روانہ' },
  'tracking.status.delivered': { en: 'Delivered', ur: 'مل گیا' },
  'tracking.status.cancelled': { en: 'Cancelled', ur: 'منسوخ' },
  'tracking.loginRequired': { en: 'Please sign in to track orders', ur: 'آرڈر ٹریک کرنے کے لیے سائن ان کریں' },
  'tracking.placeOrderTip': { en: 'Place an order from the catalog to track it here.', ur: 'آرڈر ٹریک کرنے کے لیے پہلے کیٹلاگ سے آرڈر کریں۔' },
  'tracking.items': { en: 'Items', ur: 'اشیاء' },

  'tryon.title': { en: 'Virtual Try-On', ur: 'ورچوئل ٹرائی آن' },
  'tryon.subtitle': { en: 'See how our garments look on you using AI.', ur: 'AI کے ذریعے دیکھیں کہ ہمارے ملبوسات آپ پر کیسے لگتے ہیں۔' },
  'tryon.choosePhoto': { en: 'Choose Photo', ur: 'تصویر منتخب کریں' },
  'tryon.analyzing': { en: 'Analyzing...', ur: 'تجزیہ ہو رہا ہے...' },
  'tryon.aiAssisted': { en: 'AI Assisted', ur: 'AI کی مدد سے' },
  'tryon.catalog': { en: 'Browse Catalog', ur: 'کیٹلاگ دیکھیں' },
  'tryon.uploadToSeeRecommendations': { en: 'Upload to see recommendations', ur: 'مشورے کے لیے تصویر اپ لوڈ کریں' },

  // ── Delivery Dashboard ────────────────────────────────────────────────────
  'delivery.titleA': { en: 'Delivery', ur: 'ڈیلیوری' },
  'delivery.titleB': { en: 'Panel', ur: 'پینل' },
  'delivery.welcome': { en: 'Welcome', ur: 'خوش آمدید' },
  // Stat cards
  'delivery.statPickups': { en: 'Pickups Pending', ur: 'پک اپ کے منتظر' },
  'delivery.statOnRoute': { en: 'On Route', ur: 'راستے میں' },
  'delivery.statToday': { en: 'Delivered Today', ur: 'آج پہنچائے گئے' },
  'delivery.statCash': { en: 'Cash to Collect', ur: 'وصول کرنے کی رقم' },
  // Sections
  'delivery.sectionOnRoute': { en: 'On Route', ur: 'راستے میں' },
  'delivery.sectionPickups': { en: 'Ready for Pickup', ur: 'پک اپ کے لیے تیار' },
  // Order card
  'delivery.items': { en: 'item(s)', ur: 'اشیاء' },
  'delivery.collect': { en: 'Collect on delivery', ur: 'ڈیلیوری پر وصول کریں' },
  'delivery.notes': { en: 'Notes', ur: 'نوٹس' },
  'delivery.showItems': { en: 'Show items', ur: 'اشیاء دیکھیں' },
  'delivery.hideItems': { en: 'Hide items', ur: 'اشیاء چھپائیں' },
  'delivery.openMaps': { en: 'Open in Maps', ur: 'نقشے میں کھولیں' },
  // Actions
  'delivery.startDelivery': { en: 'Start Delivery', ur: 'ڈیلیوری شروع کریں' },
  'delivery.markDelivered': { en: 'Mark Delivered', ur: 'پہنچا دیا' },
  'delivery.startedToast': { en: 'Delivery started', ur: 'ڈیلیوری شروع ہو گئی' },
  'delivery.deliveredToast': { en: 'Marked as delivered', ur: 'پہنچا دیا گیا' },
  'delivery.errorGeneric': { en: 'Could not update status', ur: 'سٹیٹس اپ ڈیٹ نہیں ہو سکا' },
  // Empty / history
  'delivery.emptyOnRoute': { en: "You're not delivering anything right now.", ur: 'ابھی کوئی ڈیلیوری نہیں ہو رہی۔' },
  'delivery.emptyPickups': { en: 'No orders waiting for pickup right now.', ur: 'پک اپ کے لیے کوئی آرڈر نہیں۔' },
  'delivery.allClear': { en: 'All clear!', ur: 'سب کام مکمل!' },
  'delivery.noOrdersAssigned': { en: 'No orders are assigned to you yet. Check back soon.', ur: 'ابھی آپ کو کوئی آرڈر تفویض نہیں ہوا۔ بعد میں دوبارہ دیکھیں۔' },
  'delivery.showHistory': { en: 'Show recent history', ur: 'حالیہ تاریخ دیکھیں' },
  'delivery.hideHistory': { en: 'Hide recent history', ur: 'حالیہ تاریخ چھپائیں' },
  'delivery.markPaid': { en: 'Mark COD Paid', ur: 'ادائیگی درج کریں' },
  'delivery.address': { en: 'Delivery Address', ur: 'ڈیلیوری کا پتہ' },
  'delivery.city': { en: 'City', ur: 'شہر' },
  'delivery.phone': { en: 'Phone', ur: 'فون' },
  'cart.paymentMethod': { en: 'Payment Method', ur: 'ادائیگی کا طریقہ' },
  'cart.card': { en: 'Online (Card)', ur: 'آن لائن (کارڈ)' },
  'cart.cod': { en: 'Cash on Delivery', ur: 'ڈیلیوری پر ادائیگی' },

  'admin.fullName': { en: 'Full Name', ur: 'پورا نام' },
  'admin.price': { en: 'Price', ur: 'قیمت' },

  // ── Password Reset & Change ────────────────────────────────────────────────
  'forgot.title1': { en: 'Forgot', ur: 'بھول' },
  'forgot.title2': { en: 'Password?', ur: 'گئے؟' },
  'forgot.email': { en: 'Email Address', ur: 'ای میل پتہ' },
  'forgot.sendCode': { en: 'Send Reset Code', ur: 'کوڈ بھیجیں' },
  'forgot.sending': { en: 'Sending...', ur: 'بھیجا جا رہا ہے...' },
  'forgot.code': { en: '6-Digit Code', ur: '6 ہندسوں کا کوڈ' },
  'forgot.newPassword': { en: 'New Password', ur: 'نیا پاس ورڈ' },
  'forgot.confirmPassword': { en: 'Confirm New Password', ur: 'پاس ورڈ کی تصدیق' },
  'forgot.resetButton': { en: 'Reset Password', ur: 'پاس ورڈ تبدیل کریں' },
  'forgot.resetting': { en: 'Resetting...', ur: 'تبدیل ہو رہا...' },
  'forgot.link': { en: 'Forgot password?', ur: 'پاس ورڈ بھول گئے؟' },
  'forgot.subtitle': { en: 'Enter your email to receive a reset code.', ur: 'ری سیٹ کوڈ حاصل کرنے کے لیے اپنا ای میل درج کریں۔' },
  'forgot.codeSentTo': { en: 'We sent a code to', ur: 'ہم نے کوڈ بھیجا ہے' },
  'forgot.resendCode': { en: 'Resend Code', ur: 'کوڈ دوبارہ بھیجیں' },
  'forgot.backToLogin': { en: 'Back to Login', ur: 'لاگ ان پر واپس جائیں' },
  'forgot.success': { en: 'Password Reset Successful!', ur: 'پاس ورڈ تبدیل ہو گیا!' },
  'forgot.redirecting': { en: 'Redirecting to login...', ur: 'لاگ ان پر جا رہے ہیں...' },
  'forgot.mismatch': { en: 'Passwords do not match', ur: 'پاس ورڈ ایک جیسے نہیں ہیں' },
  'forgot.passwordHint': { en: 'Min. 12 chars, mixed case, digit & symbol', ur: 'کم از کم 12 حروف، بڑے چھوٹے حروف، ہندسہ اور علامت' },

  'change.title': { en: 'Change Password', ur: 'پاس ورڈ تبدیل کریں' },
  'change.current': { en: 'Current Password', ur: 'موجودہ پاس ورڈ' },
  'change.new': { en: 'New Password', ur: 'نیا پاس ورڈ' },
  'change.confirm': { en: 'Confirm New Password', ur: 'پاس ورڈ کی تصدیق' },
  'change.updateButton': { en: 'Update Password', ur: 'اپ ڈیٹ کریں' },
  'change.updating': { en: 'Updating...', ur: 'اپ ڈیٹ ہو رہا ہے...' },
  'change.success': { en: 'Password updated successfully', ur: 'پاس ورڈ تبدیل ہو گیا' },
  'change.cancel': { en: 'Cancel', ur: 'منسوخ کریں' },
  'change.mismatch': { en: 'Passwords do not match', ur: 'پاس ورڈ ایک جیسے نہیں ہیں' },
  'change.sameAsCurrent': { en: 'New password must be different', ur: 'نیا پاس ورڈ مختلف ہونا چاہیے' },
  'change.strong': { en: 'Strong', ur: 'مضبوط' },
  'change.weak': { en: 'Weak', ur: 'کمزور' },
  'change.passwordHint': { en: 'Min. 12 chars, mixed case, digit & symbol', ur: 'کم از کم 12 حروف، بڑے چھوٹے حروف، ہندسہ اور علامت' },

  // ── Login / Sign Up ────────────────────────────────────────────────────────
  'login.createAccount': { en: 'Create Account', ur: 'اکاؤنٹ بنائیں' },
  'login.welcomeBack': { en: 'Welcome Back', ur: 'واپس خوش آمدید' },
  'login.joinToday': { en: 'Join TailorHub today', ur: 'آج ہی TailorHub سے جڑیں' },
  'login.signInToAccount': { en: 'Sign in to your account', ur: 'اپنے اکاؤنٹ میں سائن ان کریں' },
  'login.fullName': { en: 'Full Name', ur: 'پورا نام' },
  'login.email': { en: 'Email', ur: 'ای میل' },
  'login.password': { en: 'Password', ur: 'پاس ورڈ' },
  'login.enterName': { en: 'Enter your name', ur: 'اپنا نام درج کریں' },
  'login.yourEmail': { en: 'your@email.com', ur: 'your@email.com' },
  'login.passwordDots': { en: '••••••••', ur: '••••••••' },
  'login.forgotPassword': { en: 'Forgot password?', ur: 'پاس ورڈ بھول گئے؟' },
  'login.passwordHint': { en: 'Min 8 chars, 1 uppercase, 1 lowercase, 1 digit', ur: 'کم از کم 8 حروف، 1 بڑا، 1 چھوٹا، 1 ہندسہ' },
  'login.signUp': { en: 'Sign Up', ur: 'سائن اپ' },
  'login.signIn': { en: 'Sign In', ur: 'سائن ان' },
  'login.orContinueWith': { en: 'Or continue with', ur: 'یا اس کے ساتھ جاری رکھیں' },
  'login.continueWithGoogle': { en: 'Continue with Google', ur: 'گوگل سے جاری رکھیں' },
  'login.alreadyHaveAccount': { en: 'Already have an account?', ur: 'پہلے سے اکاؤنٹ ہے؟' },
  'login.dontHaveAccount': { en: "Don't have an account?", ur: 'اکاؤنٹ نہیں ہے؟' },
  'login.verifyEmail': { en: 'Verify Your Email', ur: 'اپنی ای میل تصدیق کریں' },
  'login.weSentCode': { en: 'We sent a 6-digit code to', ur: 'ہم نے 6 ہندسوں کا کوڈ بھیجا ہے' },
  'login.verificationCode': { en: 'Verification Code', ur: 'تصدیقی کوڈ' },
  'login.enter6DigitCode': { en: 'Enter 6-digit code', ur: '6 ہندسوں کا کوڈ درج کریں' },
  'login.verifyEmailBtn': { en: 'Verify Email', ur: 'ای میل تصدیق کریں' },
  'login.didntReceiveCode': { en: "Didn't receive the code?", ur: 'کوڈ نہیں ملا؟' },
  'login.resendCode': { en: 'Resend Code', ur: 'کوڈ دوبارہ بھیجیں' },
  'login.sending': { en: 'Sending...', ur: 'بھیجا جا رہا ہے...' },
  'login.backToLogin': { en: 'Back to Login', ur: 'لاگ ان پر واپس جائیں' },
  'login.emailVerified': { en: 'Email Verified!', ur: 'ای میل تصدیق ہو گئی!' },
  'login.redirecting': { en: 'Redirecting...', ur: 'منتقل ہو رہا ہے...' },
  'login.verifyingIdentity': { en: 'Verifying Identity', ur: 'شناخت کی تصدیق' },
  'login.connectingTo': { en: 'Connecting to', ur: 'سے منسلک ہو رہا ہے' },
  'login.socialLoginFailed': { en: 'Social login failed. Please try again or use email/password.', ur: 'سوشل لاگ ان ناکام۔ دوبارہ کوشش کریں یا ای میل/پاس ورڈ استعمال کریں۔' },
  'login.authError': { en: 'Authentication error', ur: 'توثیق کی خرابی' },
  'login.accountCreatedVerify': { en: 'Account created! Please verify your email.', ur: 'اکاؤنٹ بن گیا! براہ کرم ای میل تصدیق کریں۔' },
  'login.accountCreated': { en: 'Account created successfully.', ur: 'اکاؤنٹ کامیابی سے بن گیا۔' },
  'login.welcomeBackToast': { en: 'Welcome back!', ur: 'واپس خوش آمدید!' },
  'login.emailVerifiedToast': { en: 'Email verified successfully!', ur: 'ای میل کامیابی سے تصدیق ہو گئی!' },
  'login.pleaseSignIn': { en: 'Please sign in with your email and password.', ur: 'براہ کرم ای میل اور پاس ورڈ سے سائن ان کریں۔' },
  'login.newCodeSent': { en: 'New code sent!', ur: 'نیا کوڈ بھیج دیا گیا!' },
  'login.invalidSession': { en: 'Invalid onboarding session.', ur: 'غلط آن بورڈنگ سیشن۔' },

  // ── Change Password extras ────────────────────────────────────────────────
  'change.subtitle': { en: 'Update your account password securely', ur: 'اپنے اکاؤنٹ کا پاس ورڈ محفوظ طریقے سے اپ ڈیٹ کریں' },
  'change.minCharsHint': { en: 'Min. 8 chars, uppercase, number & symbol', ur: 'کم از کم 8 حروف، بڑا حرف، ہندسہ اور علامت' },
  'change.passwordsMatch': { en: 'Passwords match', ur: 'پاس ورڈ ایک جیسے ہیں' },
  'change.passwordsMismatch': { en: 'Passwords do not match', ur: 'پاس ورڈ ایک جیسے نہیں ہیں' },
  'change.fair': { en: 'Fair', ur: 'مناسب' },
  'change.good': { en: 'Good', ur: 'اچھا' },

  // ── Complete Profile ─────────────────────────────────────────────────────
  'complete.title': { en: 'Complete Profile', ur: 'پروفائل مکمل کریں' },
  'complete.subtitle': { en: 'Just a few more details to set up your account', ur: 'اپنا اکاؤنٹ سیٹ اپ کرنے کے لیے چند مزید تفصیلات' },
  'complete.phoneLabel': { en: 'Phone Number (Optional)', ur: 'فون نمبر (اختیاری)' },
  'complete.phonePlaceholder': { en: 'e.g. +92 300 1234567', ur: 'مثلاً +92 300 1234567' },
  'complete.addressLabel': { en: 'Default Address (Optional)', ur: 'پتہ (اختیاری)' },
  'complete.addressPlaceholder': { en: 'Your delivery address', ur: 'آپ کا ڈیلیوری کا پتہ' },
  'complete.terms': { en: 'I agree to the Terms of Service', ur: 'میں سروس کی شرائط سے متفق ہوں' },
  'complete.finalizing': { en: 'Finalizing Profile...', ur: 'پروفائل حتمی شکل دے رہے ہیں...' },
  'complete.completeBtn': { en: 'Complete Registration', ur: 'رجسٹریشن مکمل کریں' },
  'complete.profileCompleted': { en: 'Profile completed successfully. Welcome!', ur: 'پروفائل کامیابی سے مکمل ہو گیا۔ خوش آمدید!' },
  'complete.error': { en: 'Failed to complete profile.', ur: 'پروفائل مکمل کرنے میں ناکامی۔' },

  // ── Cart ──────────────────────────────────────────────────────────────────
  'cart.title': { en: 'Shopping Cart', ur: 'خریداری کا ٹوکری' },
  'cart.empty': { en: 'Your cart is empty', ur: 'آپ کا کارٹ خالی ہے' },
  'cart.browseCatalog': { en: 'Browse Catalog', ur: 'کیٹلاگ دیکھیں' },
  'cart.items': { en: 'Items', ur: 'اشیاء' },
  'cart.total': { en: 'Total', ur: 'کل رقم' },
  'cart.checkout': { en: 'Proceed to Checkout', ur: 'چیک آؤٹ کریں' },
  'cart.remove': { en: 'Remove', ur: 'ہٹائیں' },
  'cart.quantity': { en: 'Qty', ur: 'تعداد' },
  'cart.product': { en: 'Product', ur: 'پروڈکٹ' },
  'cart.subtotal': { en: 'Subtotal', ur: 'زیرِ جمع' },
  'cart.deliveryFee': { en: 'Delivery Fee', ur: 'ڈیلیوری فیس' },
  'cart.grandTotal': { en: 'Grand Total', ur: 'مجموعی رقم' },
  'cart.estimatedDelivery': { en: 'Estimated Delivery', ur: 'متوقع ڈیلیوری' },
  'cart.days': { en: 'days', ur: 'دن' },
  'cart.emptyTitle': { en: 'Your Cart is Empty', ur: 'آپ کا کارٹ خالی ہے' },
  'cart.emptySubtitle': { en: "Looks like you haven't added anything yet.", ur: 'ایسا لگتا ہے کہ آپ نے ابھی تک کچھ شامل نہیں کیا۔' },
  'cart.browseCollection': { en: 'Browse Collection', ur: 'کلیکشن دیکھیں' },
  'cart.clearCart': { en: 'Clear Cart', ur: 'کارٹ صاف کریں' },
  'cart.cartCleared': { en: 'Cart cleared', ur: 'کارٹ صاف کر دیا گیا' },
  'cart.signInRequired': { en: 'Please sign in before placing an order.', ur: 'آرڈر دینے سے پہلے سائن ان کریں۔' },
  'cart.orderPlaced': { en: 'Order placed successfully! Please pay on delivery.', ur: 'آرڈر کامیابی سے دیا گیا! براہ کرم ڈیلیوری پر ادائیگی کریں۔' },
  'cart.stripeError': { en: 'Failed to initialize Stripe session', ur: 'Stripe سیشن شروع کرنے میں ناکامی' },
  'cart.checkoutError': { en: 'Unable to process checkout', ur: 'چیک آؤٹ پراسیس نہیں ہو سکا' },
  'cart.orderSummary': { en: 'Order Summary', ur: 'آرڈر کا خلاصہ' },
  'cart.delivery': { en: 'Delivery', ur: 'ڈیلیوری' },
  'cart.processing': { en: 'Processing...', ur: 'پراسیس ہو رہا ہے...' },
  'cart.payWithStripe': { en: 'Pay with Stripe', ur: 'Stripe سے ادائیگی کریں' },
  'cart.placeCOD': { en: 'Place COD Order', ur: 'COD آرڈر دیں' },
  'cart.cancel': { en: 'Cancel', ur: 'منسوخ کریں' },
  'cart.proceedCheckout': { en: 'Proceed to Checkout', ur: 'چیک آؤٹ کریں' },
  'cart.continueShopping': { en: 'Continue Shopping', ur: 'خریداری جاری رکھیں' },
  'cart.paymentOptions': { en: 'Payment Options', ur: 'ادائیگی کے اختیارات' },
  'cart.advanceOrFull': { en: 'Advance (50%) or full payment?', ur: 'ایڈوانس (50%) یا مکمل ادائیگی؟' },
  'cart.advance50': { en: '50% Advance', ur: '50% ایڈوانس' },
  'cart.payFull': { en: 'Pay Full', ur: 'مکمل ادائیگی' },
  'cart.customSize': { en: 'Custom Size', ur: 'کسٹم سائز' },
  'cart.fillDeliveryDetails': { en: 'Please fill in all delivery details.', ur: 'براہ کرم تمام ڈیلیوری کی تفصیلات درج کریں۔' },

  // ── Admin extras ──────────────────────────────────────────────────────────
  'admin.currentInventory': { en: 'Current Inventory', ur: 'موجودہ انوینٹری' },
  'admin.itemName': { en: 'Item Name', ur: 'آئٹم کا نام' },
  'admin.stockQty': { en: 'Stock', ur: 'اسٹاک' },
  'admin.pricePerUnit': { en: 'Price/Unit', ur: 'فی یونٹ قیمت' },
  'admin.status': { en: 'Status', ur: 'حالت' },
  'admin.action': { en: 'Action', ur: 'عمل' },
  'admin.noItems': { en: 'No items in inventory', ur: 'انوینٹری میں کوئی آئٹم نہیں' },
  'admin.deduct': { en: 'Deduct', ur: 'کم کریں' },
  'admin.soldOut': { en: 'Sold Out', ur: 'فروخت ہو گیا' },
  'admin.restock': { en: 'Restock', ur: 'دوبارہ اسٹاک کریں' },
  'admin.stockDeducted': { en: 'Stock deducted', ur: 'اسٹاک کم کر دیا گیا' },
  'admin.markedSoldOut': { en: 'Marked as Sold Out', ur: 'فروخت شدہ کے طور پر نشان زد' },
  'admin.restocked': { en: 'Restocked', ur: 'دوبارہ اسٹاک کر دیا گیا' },
  'admin.itemNamePlaceholder': { en: 'Item Name (e.g. Cotton White)', ur: 'آئٹم کا نام (مثلاً سفید کپاس)' },
  'admin.quantity': { en: 'Quantity', ur: 'تعداد' },
  'admin.unit': { en: 'Unit (meters)', ur: 'یونٹ (میٹر)' },
  'admin.pricePerUnitPlaceholder': { en: 'Price per unit', ur: 'فی یونٹ قیمت' },
  'admin.lowStockThreshold': { en: 'Low Stock Threshold', ur: 'کم اسٹاک کی حد' },
  'admin.fillRequired': { en: 'Fill required fields', ur: 'ضروری خانے پُر کریں' },
  'admin.addToInventory': { en: 'Add to Inventory', ur: 'انوینٹری میں شامل کریں' },
  'admin.itemAdded': { en: 'Item added', ur: 'آئٹم شامل کر دیا گیا' },
  'admin.lowStockAlert': { en: 'LOW STOCK ALERT', ur: 'اسٹاک کم ہے' },
  'admin.soldOutBadge': { en: 'SOLD OUT', ur: 'فروخت ہو گیا' },
  
  // ── Invoices ─────────────────────────────────────────────────────────────
  'invoice.statusPaid': { en: 'Paid', ur: 'ادا شدہ' },
  'invoice.statusUnpaid': { en: 'Unpaid', ur: 'غیر ادا شدہ' },
  'invoice.statusOverdue': { en: 'Overdue', ur: 'تاخیر شدہ' },
  'invoice.statusCancelled': { en: 'Cancelled', ur: 'منسوخ' },
  'invoice.downloadSuccess': { en: 'Invoice downloaded!', ur: 'انوائس ڈاؤنلوڈ ہو گئی!' },
  'invoice.downloadError': { en: 'Failed to download invoice.', ur: 'انوائس ڈاؤنلوڈ کرنے میں ناکامی۔' },
  'invoice.myInvoices': { en: 'My Invoices', ur: 'میری انوائسز' },
  'invoice.filterAll': { en: 'All', ur: 'تمام' },
  'invoice.filterUnpaid': { en: 'Unpaid', ur: 'غیر ادا شدہ' },
  'invoice.filterPaid': { en: 'Paid', ur: 'ادا شدہ' },
  'invoice.filterOverdue': { en: 'Overdue', ur: 'تاخیر شدہ' },
  'invoice.searchPlaceholder': { en: 'Search invoice number...', ur: 'انوائس نمبر تلاش کریں...' },
  'invoice.empty': { en: 'No invoices found', ur: 'کوئی انوائس نہیں ملی' },
  'invoice.emptyDesc': { en: "You don't have any invoices matching your filters.", ur: 'آپ کے فلٹرز کے مطابق کوئی انوائس موجود نہیں۔' },
  'invoice.issueDate': { en: 'Issued', ur: 'تاریخِ اجراء' },
  'invoice.dueDate': { en: 'Due', ur: 'آخری تاریخ' },
  'invoice.actions.download': { en: 'Download PDF', ur: 'پی ڈی ایف ڈاؤنلوڈ کریں' },
  'invoice.actions.viewOrder': { en: 'View Order', ur: 'آرڈر دیکھیں' },
  'invoice.loginRequired': { en: 'Please login to view your invoices.', ur: 'اپنی انوائسز دیکھنے کے لیے لاگ ان کریں۔' },
  
  // ── Other Customer Pages ────────────────────────────────────────────────
  'vto.aiPowered': { en: 'AI Powered', ur: 'اے آئی کی طاقت سے' },
  'vto.proTip': { en: 'Pro Tip for Best Results', ur: 'بہترین نتائج کے لیے مفید مشورہ' },
  'vto.straightPosture': { en: 'Straight Posture', ur: 'سیدھی حالت میں کھڑے ہوں' },
  'vto.evenLighting': { en: 'Even Lighting', ur: 'برابر روشنی' },
  'vto.avoidShadows': { en: 'Avoid harsh shadows', ur: 'گہرے سائے سے بچیں' },
  'vto.recommendedColors': { en: 'Recommended Fabric Colors', ur: 'تجویز کردہ کپڑوں کے رنگ' },
  'vto.aiResult': { en: 'AI Result', ur: 'اے آئی نتیجہ' },
  
  'product.hoverZoom': { en: 'Hover to zoom', ur: 'زوم کرنے کے لیے اوپر لائیں' },
  'product.suitConfig': { en: 'Suit Configuration', ur: 'سوٹ کی ترتیب' },
  'product.addWaistcoat': { en: 'Add Waistcoat', ur: 'واسکٹ شامل کریں' },
  
  'payment.trackOrder': { en: 'Track My Order', ur: 'میرا آرڈر ٹریک کریں' },
  'payment.returnHome': { en: 'Return to Home', ur: 'ہوم پر واپس جائیں' },
  'payment.successTitle': { en: 'Payment Confirmed!', ur: 'ادائیگی کی تصدیق ہو گئی!' },
  'payment.successDesc': { en: 'Your payment has been securely processed by Stripe.', ur: 'آپ کی ادائیگی کو سٹرائپ کے ذریعے محفوظ طریقے سے مکمل کر لیا گیا ہے۔' },
  'payment.successOrder': { en: 'Your order ID is', ur: 'آپ کے آرڈر کی آئی ڈی ہے' },
  'payment.successKhata': { en: 'The Khata ledger has been successfully updated.', ur: 'کھاتہ لیجر کامیابی سے اپ ڈیٹ ہو گیا ہے۔' },
  
  'footer.aboutUs': { en: 'About Us', ur: 'ہمارے بارے میں' },
  'footer.privacyPolicy': { en: 'Privacy Policy', ur: 'پرائیویسی پالیسی' },
  'footer.termsOfService': { en: 'Terms of Service', ur: 'سروس کی شرائط' },
  'measurements.selectTime': { en: 'Select time slot', ur: 'وقت منتخب کریں' },

  // ── Home Page Extras ───────────────────────────────────────────────────
  'home.featuredTitle': { en: 'Featured', ur: 'منتخب' },
  'home.collection': { en: 'Collection', ur: 'کلیکشن' },
  'home.featuredSubtitle': { en: 'Handpicked pieces for the discerning gentleman', ur: 'بہترین ذوق رکھنے والوں کے لیے منتخب ملبوسات' },
  'home.viewAll': { en: 'View All', ur: 'سب دیکھیں' },
  'home.viewAllCollection': { en: 'View All Collection', ur: 'تمام کلیکشن دیکھیں' },
};

const LanguageContext = createContext(undefined);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    if (typeof window === 'undefined') return 'ur';
    const stored = localStorage.getItem('tailorhub-language');
    return stored ? stored : 'ur';
  });

  const [isChanging, setIsChanging] = useState(false);

  useEffect(() => {
    localStorage.setItem('tailorhub-language', language);
    document.documentElement.lang = language === 'ur' ? 'ur' : 'en';
  }, [language]);

  const changeLanguage = (newLang) => {
    if (newLang === language) return;
    setIsChanging(true);
    setTimeout(() => {
      setLanguage(newLang);
      setTimeout(() => setIsChanging(false), 100);
    }, 150);
  };

  const t = (key, fallback) => {
    const entry = dictionary[key];
    if (!entry) return fallback || key;
    return entry[language] || fallback || entry.en || key;
  };

  const value = useMemo(() => ({
    language,
    setLanguage: changeLanguage,
    toggleLanguage: () => changeLanguage(language === 'en' ? 'ur' : 'en'),
    t,
  }), [language]);

  return React.createElement(
    LanguageContext.Provider,
    { value: value },
    React.createElement('div', {
      style: {
        opacity: isChanging ? 0 : 1,
        transition: 'opacity 0.15s ease-in-out',
        minHeight: '100vh'
      }
    }, children)
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};
